const products = [
  {
    _id: '1',
    name: 'Marvel Skull T-Shirt',
    image: '/images/muska-majica-marvel.png',
    description:
      'Muska majica kratkih rukava, 100% pamuk, Marvel Skull',
    brand: 'Marvel',
    category: 'T-Shirt',
    price: 69.99,
    countInStock: 10,
    rating: 4.5,
    numReviews: 12,
  },
  {
    _id: '2',
    name: 'Houose Brand T-Shirt',
    image: '/images/muska-majica-house-brand.png',
    description:
      'Muska majica kratkih rukava, 100% pamuk, House Brand',
    brand: 'House',
    category: 'T-Shirt',
    price: 69.99,
    countInStock: 7,
    rating: 3.0,
    numReviews: 8,
  },
  {
    _id: '3',
    name: 'Blue Sky Sweatshirt',
    image: '/images/muska-dukserica.png',
    description:
      'Muska dukserica, 100% pamuk, Jack&Jones',
    brand: 'Jack&Jones',
    category: 'Sweatshirt',
    price: 129.99,
    countInStock: 5,
    rating: 4,
    numReviews: 12,
  },
  {
    _id: '4',
    name: 'Red Meadow Dress',
    image: '/images/zenska-haljina.jpg',
    description:
      'Ženska haljuna, 100% pamuk, House',
    brand: 'House',
    category: 'Dress',
    price: 159.99,
    countInStock: 11,
    rating: 5,
    numReviews: 12,
  },
  {
    _id: '5',
    name: 'Hipi Sky Shirt',
    image: '/images/zenska-kosulja.jpg',
    description:
      'Ženska kosulja, 100% pamuk, House',
    brand: 'House',
    category: 'Shirt',
    price: 79.99,
    countInStock: 7,
    rating: 3.5,
    numReviews: 10,
  },
  {
    _id: '6',
    name: 'Yellow Star Sneakers',
    image: '/images/zenske-tenisice.jpg',
    description:
      'Zenske tenisice, microfibra',
    brand: 'Addidas',
    category: 'Sneakers',
    price: 199.99,
    countInStock: 2,
    rating: 4,
    numReviews: 12,
  },
  {
    _id: '7',
    name: 'Buisines Man Sneakers',
    image: '/images/muske-tenisice.jpg',
    description:
      'Muske tenisice, microfibra',
    brand: 'Addidas',
    category: 'Sneakers',
    price: 209.99,
    countInStock: 4,
    rating: 5,
    numReviews: 8,
  },
]

export default products
